AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Metadata: {}
Parameters: {}
Mappings: {}
Conditions: {}
Resources:
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub '10.251.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: vpc
Outputs: {}
